Add web scraping functionality
RonnyFrayRegato/discord-bot pull request #3
Opened 2022-10-16 23:52 UTC by Andrew-Wilhelm

Add web scraping functionallity to the Discord bot.

2022-10-18 03:57 UTC, RonnyFrayRegato commented on scraping_google_images.py
> +PATH = r'C:\Users\Andrew Wilhelm\OneDrive - Florida Gulf Coast University\4th year 2022-2023\Fall 2022\CNT 4104 Software Proj Comp Networks\seleniumImage\Chrome Driver\chromedriver.exe'
@Andrew-Wilhelm The process of pulling the ChromeDriver needs to be automated. I recommend reading the following documentation to assist with this task: https://www.selenium.dev/documentation/webdriver/getting_started/install_drivers/

2022-10-28 02:58 UTC, AlexisMLopez requested changes

2022-10-28 02:58 UTC, AlexisMLopez commented on scraping_google_images.py
> +        # get the IO output bytes fo the image
Typo in comment

2022-10-28 03:07 UTC, AlexisMLopez approved these changes

2022-10-28 03:13 UTC, Andrew-Wilhelm commented
I have fixed all typos

2022-10-28 03:14 UTC, RonnyFrayRegato approved these changes

2022-10-28 03:20 UTC, merged